//export const REQUEST_NEW_SUBMISSION = 'REQUEST_NEW_SUBMISSION'
//export const RECEIVE_NEW_SUBMISSION = 'RECEIVE_NEW_SUBMISSION'

export const REQUEST_INSTITUTIONS = 'REQUEST_INSTITUTIONS'
export const RECEIVE_INSTITUTIONS = 'RECEIVE_INSTITUTIONS'

export const REQUEST_INSTITUTION = 'REQUEST_INSTITUTION'
export const RECEIVE_INSTITUTION = 'RECEIVE_INSTITUTION'

export const CLEAR_FILINGS = 'CLEAR_FILINGS'

export const SELECT_FILE = 'SELECT_FILE'
export const REQUEST_UPLOAD = 'REQUEST_UPLOAD'
export const UPLOAD_START = 'UPLOAD_START'
export const UPLOAD_PROGRESS = 'UPLOAD_PROGRESS'
export const UPLOAD_COMPLETE = 'UPLOAD_COMPLETE'
export const UPLOAD_ERROR = 'UPLOAD_ERROR'

export const REQUEST_SUBMISSION = 'REQUEST_SUBMISSION'
export const RECEIVE_SUBMISSION = 'RECEIVE_SUBMISSION'

export const REQUEST_EDITS_BY_TYPE = 'REQUEST_EDITS_BY_TYPE'
export const REQUEST_EDITS_BY_ROW = 'REQUEST_EDITS_BY_ROW'
export const RECEIVE_EDITS_BY_TYPE = 'RECEIVE_EDITS_BY_TYPE'
export const RECEIVE_EDITS_BY_ROW = 'RECEIVE_EDITS_BY_ROW'

export const REQUEST_IRS_REPORT = 'REQUEST_IRS_REPORT'
export const RECEIVE_IRS_REPORT = 'RECEIVE_IRS_REPORT'

//export const REQUEST_VALIDATION_PROGRESS = 'REQUEST_VALIDATION_PROGRESS'
//export const RECEIVE_VALIDATION_PROGRESS = 'RECEIVE_VALIDATION_PROGRESS'

//export const VIEW_HOMEPAGE= 'VIEW_HOMEPAGE'
