//export const REQUEST_NEW_SUBMISSION = 'REQUEST_NEW_SUBMISSION'
//export const RECEIVE_NEW_SUBMISSION = 'RECEIVE_NEW_SUBMISSION'

export const REQUEST_INSTITUTIONS = 'REQUEST_INSTITUTIONS'
export const RECEIVE_INSTITUTIONS = 'RECEIVE_INSTITUTIONS'

export const REQUEST_INSTITUTION = 'REQUEST_INSTITUTION'
export const RECEIVE_INSTITUTION = 'RECEIVE_INSTITUTION'

//export const REQUEST_UPLOAD = 'REQUEST_UPLOAD'
//export const RECEIVE_UPLOAD = 'RECEIVE_UPLOAD'

export const CLEAR_FILINGS = 'CLEAR_FILINGS'

//export const REQUEST_VALIDATION_PROGRESS = 'REQUEST_VALIDATION_PROGRESS'
//export const RECEIVE_VALIDATION_PROGRESS = 'RECEIVE_VALIDATION_PROGRESS'

//export const VIEW_SUBMISSION = 'VIEW_SUBMISSION'
//export const VIEW_HOMEPAGE= 'VIEW_HOMEPAGE'
