export const RECEIVE_AUTH_USER      = 'RECEIVE_AUTH_USER'

export const REQUEST_INSTITUTIONS   = 'REQUEST_INSTITUTIONS'
export const RECEIVE_INSTITUTIONS   = 'RECEIVE_INSTITUTIONS'

export const REQUEST_INSTITUTION    = 'REQUEST_INSTITUTION'
export const RECEIVE_INSTITUTION    = 'RECEIVE_INSTITUTION'

export const REQUEST_EDIT_POST       = 'REQUEST_EDIT_POST'
export const RECEIVE_EDIT_POST       = 'RECEIVE_EDIT_POST'

export const UPDATE_FILING_PERIOD   = 'UPDATE_FILING_PERIOD'
export const CLEAR_FILINGS          = 'CLEAR_FILINGS'

export const PICK_SORT              = 'PICK_SORT'

export const SELECT_FILE            = 'SELECT_FILE'
export const REQUEST_UPLOAD         = 'REQUEST_UPLOAD'
export const UPLOAD_START           = 'UPLOAD_START'
export const UPLOAD_PROGRESS        = 'UPLOAD_PROGRESS'
export const UPLOAD_COMPLETE        = 'UPLOAD_COMPLETE'
export const UPLOAD_ERROR           = 'UPLOAD_ERROR'

export const REQUEST_FILING         = 'REQUEST_FILING'
export const RECEIVE_FILING         = 'RECEIVE_FILING'


export const RECEIVE_SUBMISSION     = 'RECEIVE_SUBMISSION'

export const REQUEST_EDITS_BY_TYPE  = 'REQUEST_EDITS_BY_TYPE'
export const REQUEST_EDITS_BY_ROW   = 'REQUEST_EDITS_BY_ROW'
export const RECEIVE_EDITS_BY_TYPE  = 'RECEIVE_EDITS_BY_TYPE'
export const RECEIVE_EDITS_BY_ROW   = 'RECEIVE_EDITS_BY_ROW'

export const REQUEST_IRS            = 'REQUEST_IRS'
export const RECEIVE_IRS            = 'RECEIVE_IRS'
export const REQUEST_IRS_POST       = 'REQUEST_IRS_POST'
export const RECEIVE_IRS_POST       = 'RECEIVE_IRS_POST'

export const REQUEST_SUMMARY        = 'REQUEST_SUMMARY'
export const RECEIVE_SUMMARY        = 'RECEIVE_SUMMARY'

export const REQUEST_PARSE_ERRORS   = 'REQUEST_PARSE_ERRORS'
export const RECEIVE_PARSE_ERRORS   = 'RECEIVE_PARSE_ERRORS'

export const REQUEST_SIGNATURE      = 'REQUEST_SIGNATURE'
export const RECEIVE_SIGNATURE      = 'RECEIVE_SIGNATURE'
export const REQUEST_SIGNATURE_POST = 'REQUEST_SIGNATURE_POST'
export const RECEIVE_SIGNATURE_POST = 'RECEIVE_SIGNATURE_POST'
export const POST_SIGNATURE         = 'POST_SIGNATURE'
export const CHECK_SIGNATURE        = 'CHECK_SIGNATURE'

export const UPDATE_STATUS          = 'UPDATE_STATUS'
